export enum TaskTypeEnum {
  PICKUP,
  DELIVERY,
}

export enum ShipmentItemStatusEnum {
  UNKNOWN = 0,
  SHIPPING_REQUESTED = 1,
  PICKUP_CANCELLED = 2,
  PICKUP_DONE = 10,
  LOADED = 20,
  UNLOADED = 30,
  DELIVERED = 40,
  NOT_FOUND = 90,
  MISSING = 100,
  DAMAGED = 110,
}

export enum DailyMissionStatus {
  START_OF_DAY = 1,
  WAITING_FOR_EXIT_REQUEST_APPROVAL = 2,
  EXIT_REQUEST_APPROVED = 3,
  MISSION_STARTED = 4,
  MISSION_COMPLETED = 5,
  RECONCILED = 6,
}

export enum TaskStatusEnum {
  UNKNOWN,
  ASSIGNED,
  FORWARDED,
  REJECTED,
  COMPLETED,
  CANCELLED,
  SUSPENDED,
  WAITING_TO_BE_ASSIGNED,
}
