export const TRANSLATE: any = {
  OTHER: 'Diğer',
  PRICING_PROBLEM: 'Fiyat problemleri',
  BANNED_SHIPPING_CONTENT: 'Taşınması yasak kargo',
  CONTENT_DAMAGED: 'Gönderi hasarlı',
  DELIVERY_CANCELLED: 'Gönderi durduruldu. Teslim etmeyiniz!',
  PICKUP_DATE_CHANGED: 'Bu göreve toplama randevusu girildi',
  SENDER_PERSONAL_INFO_CHANGED: 'Gönderici bilgileri değişti',
  WORKPLACE_CLOSED: 'İşyeri kapalı olarak belirtildi',
  ADDRESS_CHANGED: 'Adres değişikliği',
  UNKNOWN: 'BİLİNMEYEN',
  ASSIGNED: 'ATANDI',
  FORWARDED: 'YÖNLENDİRİLDİ',
  REJECTED: ' REDDEDİLDİ',
  COMPLETED: 'TAMAMLANDI',
  CANCELLED: 'İPTAL EDİLDİ',
  SUSPENDED: 'BEKLEMEDE',
};
